import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { createHash } from 'node:crypto';
import sharp from 'sharp';
import { fixture } from './watermarks.test.mjs';
import { largeJpegFixture } from './fixtures/watermark-output.mjs';
import { outlineFixture } from './fixtures/watermark-outline.mjs';

test('admin watermark API: access control, preservation, live image serving and no publication', async t => {
  const directory = await mkdtemp(path.join(tmpdir(), 'wangs-watermark-test-'));
  const listener = createServer();
  await new Promise(resolve => listener.listen(0, '127.0.0.1', resolve));
  const port = listener.address().port;
  await new Promise(resolve => listener.close(resolve));
  const origin = `http://127.0.0.1:${port}`;
  const child = spawn(process.execPath, ['node_modules/next/dist/bin/next', 'start', '--hostname', '127.0.0.1', '--port', String(port)], {
    cwd: process.cwd(), env: { ...process.env, ADMIN_PASSWORD: 'watermark-fixture-password', ADMIN_SESSION_SECRET: 'watermark-fixture-session-secret', LOCATION_DB_PATH: path.join(directory, 'test.sqlite'), WATERMARK_TEMPLATE_DIR: path.join(directory, 'templates') }, stdio: ['ignore', 'pipe', 'pipe'],
  });
  let logs = '', rawDirectory, processedDirectory, manifestDirectory;
  child.stdout.on('data', chunk => { logs += chunk; });
  child.stderr.on('data', chunk => { logs += chunk; });
  t.after(async () => {
    if (child.exitCode === null) { child.kill('SIGTERM'); await new Promise(resolve => child.once('exit', resolve)); }
    if (rawDirectory) await rm(rawDirectory, { recursive: true, force: true });
    if (processedDirectory) await rm(processedDirectory, { recursive: true, force: true });
    if (manifestDirectory) await rm(manifestDirectory, { recursive: true, force: true });
    await rm(directory, { recursive: true, force: true });
  });
  let ready = false;
  for (let i = 0; i < 100; i++) {
    try { if ((await fetch(origin)).ok) { ready = true; break; } } catch {}
    if (child.exitCode !== null) throw new Error(logs);
    await new Promise(resolve => setTimeout(resolve, 100));
  }
  assert.ok(ready, logs);
  const endpoint = `${origin}/api/admin/articles/watermarks`;
  assert.equal((await fetch(endpoint)).status, 401);
  assert.equal((await fetch(endpoint, { method: 'POST', body: '{}' })).status, 401);
  const login = await fetch(`${origin}/api/admin/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password: 'watermark-fixture-password' }) });
  const cookie = login.headers.get('set-cookie').split(';')[0];
  const headers = { 'Content-Type': 'application/json', Cookie: cookie };
  const post = (body, extra = {}) => fetch(endpoint, { method: 'POST', headers: { ...headers, ...extra }, body: JSON.stringify(body) });
  assert.equal((await (await fetch(endpoint, { headers })).json()).settings, null);
  const created = await fetch(`${origin}/api/admin/articles`, { method: 'POST', headers, body: JSON.stringify({ title: '图片去水印功能测试', summary: '仅供本地测试，不发布、不上传', content: '<p>测试正文</p>', status: 'draft' }) });
  const article = (await created.json()).article;
  assert.ok(article?.id);
  const f = await fixture();
  const filename = `${createHash('sha256').update(f.input).digest('hex').slice(0, 24)}.png`;
  rawDirectory = path.join(process.cwd(), 'public', 'uploads', 'articles', article.id);
  processedDirectory = path.join(process.cwd(), 'public', 'article-images', article.id);
  manifestDirectory = path.join(process.cwd(), 'data', 'watermark-manifests', article.id);
  await mkdir(rawDirectory, { recursive: true });
  await writeFile(path.join(rawDirectory, filename), f.input);
  const blackFixture = await fixture(1, [20, 20, 20]);
  const blackFilename = `${createHash('sha256').update(blackFixture.input).digest('hex').slice(0, 24)}.png`;
  await writeFile(path.join(rawDirectory, blackFilename), blackFixture.input);
  const blackSource = `/uploads/articles/${article.id}/${blackFilename}`;
  const source = `/uploads/articles/${article.id}/${filename}`;
  const content = `<p>这是测试图片，去水印不会自动修改或发布正文。</p><img src="${source}"><img src="${blackSource}">`;
  const savedResponse = await fetch(`${origin}/api/admin/articles/${article.id}`, { method: 'PUT', headers, body: JSON.stringify({ ...article, content }) });
  const saved = (await savedResponse.json()).article;
  const settings = { ...f.settings, template: f.template.toString('base64') };
  const body = { action: 'process', authorized: true, articleId: article.id, source, content, settings };
  assert.equal((await post(body, { Origin: 'https://untrusted.invalid' })).status, 403);
  assert.equal((await post({ ...body, authorized: false })).status, 422);
  assert.equal((await post({ ...body, content: '<p>no image</p>' })).status, 422);
  assert.equal((await post({ ...body, content: `<img src="${source}">`.repeat(101) })).status, 422);
  for (const count of [69, 100]) {
    const accepted = await post({ ...body, content: `<img src="${source}">`.repeat(count) });
    const acceptedBody = await accepted.json();
    assert.equal(accepted.status, 200, `${count} image tags must pass the new limit: ${JSON.stringify(acceptedBody)}`);
    assert.equal(acceptedBody.status, 'processed');
  }
  for (const invalid of ['http://127.0.0.1/secret.png', `/uploads/articles/${crypto.randomUUID()}/${filename}`, `/uploads/articles/${article.id}/../../.env.local`, `/article-images/${article.id}/${filename}`]) {
    assert.equal((await post({ ...body, source: invalid, content: `<img src="${invalid}">` })).status, 422);
  }
  const calibration = { ...body, action: 'calibrate', region: [f.left / f.width, f.top / f.height, f.tw / f.width, f.th / f.height] };
  const calibrated = await post(calibration);
  assert.equal(calibrated.status, 200);
  const yellowSettings = (await calibrated.json()).settings;
  assert.ok(yellowSettings.template);
  assert.equal(yellowSettings.extractionColor, 'yellow', 'Legacy callers without color still extract yellow');
  const blackCalibration = await post({ ...calibration, source: blackSource, color: 'black' });
  const blackResponse = await blackCalibration.json();
  assert.equal(blackCalibration.status, 200, JSON.stringify(blackResponse));
  const blackSettings = blackResponse.settings;
  assert.equal(blackSettings.extractionColor, 'black');
  assert.notEqual(blackSettings.template, yellowSettings.template);
  assert.deepEqual((await (await fetch(endpoint, { headers })).json()).settings, blackSettings);
  for (const color of ['red', null, 1, {}]) {
    const invalid = await post({ ...calibration, color });
    assert.equal(invalid.status, 422);
    assert.match((await invalid.json()).detail, /颜色/);
  }
  const wrongColor = await post({ ...calibration, color: 'black' });
  assert.equal(wrongColor.status, 422);
  assert.match((await wrongColor.json()).detail, /黑色/);
  assert.deepEqual((await (await fetch(endpoint, { headers })).json()).settings, blackSettings, 'Failed extraction must preserve the saved black template');
  // High-resolution input and large selections must no longer hit the old
  // 12 MP guard, and rejected oversized input must not replace the template.
  const largeInput = await sharp(f.input).resize(6400, 4800, { kernel: 'nearest' }).png().toBuffer();
  const largeFilename = `${createHash('sha256').update(largeInput).digest('hex').slice(0, 24)}.png`;
  await writeFile(path.join(rawDirectory, largeFilename), largeInput);
  const largeSource = `/uploads/articles/${article.id}/${largeFilename}`;
  const largeCalibrated = await post({ ...calibration, source: largeSource, content: `<img src="${largeSource}">` });
  const largePayload = await largeCalibrated.json();
  assert.equal(largeCalibrated.status, 200, JSON.stringify(largePayload));
  assert.equal(largePayload.settings.relativeWidth, f.tw / f.width);
  const largeTemplate = await sharp(Buffer.from(largePayload.settings.template, 'base64')).metadata();
  assert.ok(largeTemplate.width * largeTemplate.height <= 1_000_000);
  const excessiveInput = await sharp({ create: { width: 8001, height: 5000, channels: 3, background: '#ffffff' } }).png().toBuffer();
  const excessiveFilename = `${createHash('sha256').update(excessiveInput).digest('hex').slice(0, 24)}.png`;
  await writeFile(path.join(rawDirectory, excessiveFilename), excessiveInput);
  const excessiveSource = `/uploads/articles/${article.id}/${excessiveFilename}`;
  const rejectedLarge = await post({ ...calibration, source: excessiveSource, content: `<img src="${excessiveSource}">` });
  assert.equal(rejectedLarge.status, 422);
  assert.match((await rejectedLarge.json()).detail, /4000 万像素/);
  assert.deepEqual((await (await fetch(endpoint, { headers })).json()).settings, largePayload.settings);
  assert.deepEqual(await readFile(path.join(rawDirectory, largeFilename)), largeInput, 'Calibration never resizes the raw file');
  const blackProcessed = await post({ ...body, source: blackSource, settings: blackSettings });
  const blackResult = await blackProcessed.json();
  assert.equal(blackProcessed.status, 200, JSON.stringify(blackResult));
  assert.equal(blackResult.status, 'processed');
  assert.equal(blackResult.platformWatermark.text, '深巷');
  assert.equal((await fetch(origin + blackResult.localUrl)).status, 200);
  assert.deepEqual(await readFile(path.join(rawDirectory, blackFilename)), blackFixture.input);
  assert.equal((await post({ action: 'save-template', authorized: true, settings })).status, 200);
  const processed = await post(body);
  assert.equal(processed.status, 200);
  const result = await processed.json();
  assert.equal(result.status, 'processed', JSON.stringify(result));
  assert.equal(result.platformWatermark.text, '深巷');
  assert.equal(result.platformWatermark.opacity, 179);
  assert.match(result.reason, /已添加.*深巷/);
  assert.match(result.localUrl, new RegExp(`^/article-images/${article.id}/[0-9a-f]{24}\\.png$`));
  const image = await fetch(origin + result.localUrl);
  assert.equal(image.status, 200, 'New images must be visible without restarting Next');
  assert.equal(image.headers.get('content-type'), 'image/png');
  const bytes = Buffer.from(await image.arrayBuffer());
  const outputName = result.localUrl.split('/').at(-1);
  assert.deepEqual(bytes, await readFile(path.join(processedDirectory, outputName)));
  assert.deepEqual(await readFile(path.join(rawDirectory, filename)), f.input);
  const manifestName = outputName.replace('.png', '.json');
  assert.equal((await fetch(`${origin}/article-images/${article.id}/${manifestName}`)).status, 404);
  const manifest = JSON.parse(await readFile(path.join(manifestDirectory, manifestName), 'utf8'));
  assert.equal(manifest.sourceHash, createHash('sha256').update(f.input).digest('hex'));
  assert.equal(manifest.outputHash, createHash('sha256').update(bytes).digest('hex'));
  assert.equal(manifest.version, 2);
  assert.equal(manifest.platformWatermark.text, '深巷');
  assert.equal(manifest.platformWatermark.transparencyPercent, 30);
  const articles = await (await fetch(`${origin}/api/admin/articles`, { headers })).json();
  assert.deepEqual(articles.articles.find(a => a.id === article.id), saved, 'Processing cannot save or publish the article');
  assert.equal((await fetch(`${origin}/articles/${article.id}`)).status, 404);
  const concurrent = await Promise.all([post(body), post(body)]);
  assert.deepEqual(concurrent.map(r => r.status).sort(), [200, 429]);
  const oversized = await largeJpegFixture();
  const oversizedFilename = `${createHash('sha256').update(oversized.input).digest('hex').slice(0, 24)}.jpg`;
  await writeFile(path.join(rawDirectory, oversizedFilename), oversized.input);
  const oversizedSource = `/uploads/articles/${article.id}/${oversizedFilename}`;
  const compressedRequest = { ...body, source: oversizedSource, content: `<img src="${oversizedSource}">`, settings: { ...oversized.settings, template: oversized.template.toString('base64'), allowLossyOutput: true } };
  const compressedResponse = await post(compressedRequest);
  const compressed = await compressedResponse.json();
  assert.equal(compressedResponse.status, 200, JSON.stringify(compressed));
  assert.equal(compressed.status, 'processed', JSON.stringify(compressed));
  assert.equal(compressed.output.format, 'jpeg');
  assert.equal(compressed.output.lossy, true);
  assert.equal(compressed.output.width, oversized.width);
  assert.equal(compressed.output.height, oversized.height);
  assert.ok(compressed.output.byteLength <= 8 * 1024 * 1024);
  assert.match(compressed.localUrl, /\/[a-f0-9]{24}\.jpg$/);
  assert.match(compressed.reason, /有损压缩/);
  const compressedImage = await fetch(origin + compressed.localUrl);
  assert.equal(compressedImage.status, 200);
  assert.equal(compressedImage.headers.get('content-type'), 'image/jpeg');
  const compressedBytes = Buffer.from(await compressedImage.arrayBuffer());
  assert.equal((await sharp(compressedBytes).metadata()).format, 'jpeg');
  assert.equal(compressedBytes.length, compressed.output.byteLength);
  const compressedManifestName = `${path.parse(compressed.localUrl).name}.json`;
  const compressedManifest = JSON.parse(await readFile(path.join(manifestDirectory, compressedManifestName), 'utf8'));
  assert.deepEqual(compressedManifest.output, compressed.output);
  assert.equal(compressedManifest.outputHash, createHash('sha256').update(compressedBytes).digest('hex'));
  assert.deepEqual(await readFile(path.join(rawDirectory, oversizedFilename)), oversized.input);
  const afterCompression = await (await fetch(`${origin}/api/admin/articles`, { headers })).json();
  assert.deepEqual(afterCompression.articles.find(a => a.id === article.id), saved, 'Compression never applies or publishes the preview');
  const outlined = await outlineFixture();
  const outlinedFilename = `${createHash('sha256').update(outlined.input).digest('hex').slice(0, 24)}.png`;
  await writeFile(path.join(rawDirectory, outlinedFilename), outlined.input);
  const outlinedSource = `/uploads/articles/${article.id}/${outlinedFilename}`;
  const outlinedContent = `<p>合成描边水印测试，不发布</p><img src="${outlinedSource}">`;
  const outlinedCalibration = { ...calibration, source: outlinedSource, content: outlinedContent, region: outlined.region, color: 'yellow-outline', outlineRadius: 4 };
  const outlinedResponse = await post(outlinedCalibration);
  const outlinedPayload = await outlinedResponse.json();
  assert.equal(outlinedResponse.status, 200, JSON.stringify(outlinedPayload));
  const outlinedSettings = outlinedPayload.settings;
  assert.equal(outlinedSettings.extractionColor, 'yellow-outline');
  assert.equal(outlinedSettings.search, 'bottom');
  assert.equal(outlinedSettings.padding, 1);
  assert.equal(outlinedSettings.mode, 'inpaint');
  assert.equal(outlinedSettings.outlineRadius, 4);
  assert.deepEqual((await (await fetch(endpoint, { headers })).json()).settings, outlinedSettings);
  for (const outlineRadius of [0, 13, 1.5, '4', null]) {
    const rejected = await post({ ...outlinedCalibration, outlineRadius });
    assert.equal(rejected.status, 422);
    assert.match((await rejected.json()).detail, /描边/);
  }
  assert.equal((await post({ action: 'save-template', authorized: true, settings: { ...outlinedSettings, mode: 'inverse' } })).status, 422);
  assert.equal((await post({ action: 'save-template', authorized: true, settings: { ...outlinedSettings, outlineRadius: 99 } })).status, 422);
  assert.deepEqual((await (await fetch(endpoint, { headers })).json()).settings, outlinedSettings, 'Invalid outlined calibration/save must not replace the saved template');
  const outlinedProcessed = await post({ ...body, source: outlinedSource, content: outlinedContent, settings: outlinedSettings });
  const outlinedResult = await outlinedProcessed.json();
  assert.equal(outlinedProcessed.status, 200, JSON.stringify(outlinedResult));
  assert.equal(outlinedResult.status, 'processed', JSON.stringify(outlinedResult));
  assert.equal(outlinedResult.platformWatermark.text, '深巷');
  const outlinedImage = await fetch(origin + outlinedResult.localUrl);
  assert.equal(outlinedImage.status, 200);
  assert.equal(outlinedImage.headers.get('content-type'), 'image/png');
  assert.deepEqual(await readFile(path.join(rawDirectory, outlinedFilename)), outlined.input);
  const outlinedManifest = JSON.parse(await readFile(path.join(manifestDirectory, `${path.parse(outlinedResult.localUrl).name}.json`), 'utf8'));
  assert.equal(outlinedManifest.settings.extractionColor, 'yellow-outline');
  assert.equal(outlinedManifest.settings.search, 'bottom');
  assert.equal(outlinedManifest.settings.outlineRadius, 4);
  const afterOutline = await (await fetch(`${origin}/api/admin/articles`, { headers })).json();
  assert.deepEqual(afterOutline.articles.find(a => a.id === article.id), saved, 'Outlined processing never saves or publishes the article');
  if (process.env.WATERMARK_UI_REVIEW === '1') {
    console.log(`UI fixture: http://localhost:${port}/ops-7q4m/editor?id=${article.id}`);
    console.log('Fixture-only login: watermark-fixture-password. Press Enter here after UI checks.');
    process.stdin.resume();
    await new Promise(resolve => process.stdin.once('data', resolve));
    process.stdin.pause();
  }
});
